# Generated by Django 5.2 on 2025-05-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FunkoPop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('link_image', models.CharField(max_length=300)),
                ('cost', models.IntegerField(default=0)),
            ],
        ),
    ]
