# Generated by Django 5.2 on 2025-05-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funkopop',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
