# Generated by Django 5.2 on 2025-05-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_funkopop_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='funkopop',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
