# Generated by Django 5.2 on 2025-05-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='funkos',
            field=models.ManyToManyField(related_name='funkos', to='mainApp.funkopop'),
        ),
    ]
