# Generated by Django 5.2 on 2025-06-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_review_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wishedFunkos',
            field=models.ManyToManyField(related_name='wishedFunkos', to='mainApp.funkopop'),
        ),
    ]
